# Generated by Django 4.2.8 on 2025-12-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if uploaded from web', null=True)),
                ('calories', models.FloatField(default=0, help_text='Estimated calories (kcal)')),
                ('protein', models.FloatField(default=0, help_text='Protein in grams')),
                ('carbs', models.FloatField(default=0, help_text='Carbohydrates in grams')),
                ('fat', models.FloatField(default=0, help_text='Fat in grams')),
                ('food_item', models.CharField(blank=True, help_text='Identified food item', max_length=255)),
                ('portion_size', models.CharField(blank=True, default='1 plate', help_text='Estimated portion size', max_length=100)),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence level (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_nutriti_created_eb95df_idx'), models.Index(fields=['user', '-created_at'], name='api_nutriti_user_id_43a393_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique_for_date='user')),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('scan_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
